[[redirects]]
  from = "https://www.getistio.io"
  to = "https://istio.tetratelabs.io"
  status = 301
  force = true

[[redirects]]
  from = "https://getistio.io"
  to = "https://istio.tetratelabs.io"
  status = 301
  force = true